In [ ]:
!pip install kora -q
from kora.selenium import wd
import pandas as pd

     |████████████████████████████████| 61kB 2.3MB/s
     |████████████████████████████████| 61kB 4.8MB/s

In [ ]:
# url="https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-hinjewadi-phase-2-pune-1070-sq-ft-spid-L53049788"
def link_data(link_url):
  wd.get(link_url)
  try:
    specification=wd.find_element_by_class_name("banner__sizePropType").text[0:5]
  except:
    try:
      specification=wd.find_element_by_id("bedWash").text[:5]
    except:
      specification=None

  # project=wd.find_element_by_class_name("banner__projectName").text
  try:
    floors=wd.find_element_by_id("floorCountSociety").text
  except:
    try:
      floors=wd.find_element_by_id("floorNumLabel").text[0]
    except:
      floors=None
  try:
    status=wd.find_element_by_class_name("factTableComponent__npPossession").text
  except:
    try:
      status=wd.find_element_by_id("Availability_Lbl").text
    except:
      status=None

  try:
    poss=wd.find_element_by_xpath("/html/body/div[1]/div/div/div/div[3]/div/div[2]/div[1]/div[3]/div/div[2]/span[2]").text
  except:
    try:
        poss=wd.find_element_by_id("agePossessionLbl").text
    except:
      poss=None

    # area=wd.find_element_by_xpath("/html/body/div[1]/div/div/div/div[3]/div/div[2]/div[1]/div[2]/div[1]/span").text

  # price=wd.find_element_by_xpath("/html/body/div[1]/div/div/div/div[3]/div/div[2]/div[1]/div[1]/div[2]/span[3]").text

  try:
    basic_amenities=wd.find_element_by_id("xidAmeWrap").text.split('\n')
  except:
    try:
      basic_amenities=wd.find_element_by_id("features").text.split('\n')
    except:
      basic_amenities=None

  try:
    lifestyle=wd.find_element_by_id("lifeStyleWrp").text.split('\n')
  except:
    lifestyle=None

  try:
    transaction_type=wd.find_element_by_id("Transact_Type_Label").text
  except:
    transaction_type="New sale"

  item={
      'specification':specification,
      # 'project':project,
      'floors':floors,
      'status':status,
      'possession':poss,
      # 'area':area,
      # 'price':price,
      'basic_amenities':basic_amenities,
      'lifestyle':lifestyle,
      'transaction_type':transaction_type
  }
  return item
# print(link_data(url))

In [ ]:
base_url="https://www.99acres.com/property-in-hinjewadi-pune-ffid-page-"

def dataset(url,n):
  all_items=[]#store all rows as a list of dict
  posted_by=[]
  
  for i in range(1,n):

    wd.get(url+str(i))
    tables=wd.find_elements_by_class_name("srpTuple__tupleTable")
    dealers=wd.find_elements_by_class_name("srpTuple__srpDealerInfo")

    for d in dealers:
      name=d.find_element_by_class_name("list_header_semiBold").text
      posted_by.append(name)
   
    for table in tables:
      # try:
      #   Specification=table.find_element_by_xpath('.//*[@id="srp_tuple_property_title"]/h2').text
      # except:
      #   Specification=None
      try:
        Project=table.find_element_by_xpath('.//*[@id="srp_tuple_society_heading"]/a').text
      except:
        Project=None
      try:
        Area=table.find_element_by_xpath('.//*[@id="srp_tuple_primary_area"]').text
      except:
        Area=None
      try:
        sqft=table.find_element_by_xpath('.//*[@id="srp_tuple_primary_area_unit"]').text
      except:
        sqft=None
      try:
        sqmt=table.find_element_by_xpath('.//*[@id="srp_tuple_secondary_area"]').text
      except:
        sqmt=None
      try:
        Area=Area.replace(sqft,'')
        Area=Area.replace(sqmt,'')
        Area=Area.replace('\n','')
        Area=Area.replace(',','')
      except:
        None
      try:
        Area=Area[:Area.index('-')]
        Area=float(Area)
      except:
        None
      try:
        #price per sqft
        Price=table.find_element_by_xpath('.//*[@id="srp_tuple_price_per_unit_area"]').text
        Price=Price.replace('/sq.ft.','')
        Price=Price.replace(',','')
        Price=Price.replace('₹','')
        Price=float(Price)
      except:
        Price=None
      try:
        Link=table.find_element_by_tag_name('a').get_attribute('href')
      except:
        Link=None
      print(Link)
      # other_fields=link_data(Link)
      
  
      item={
          # 'specification':other_fields['specification'],
          # 'floors':other_fields['floors'],
          # 'status':other_fields['status'],
          # 'transaction_type':other_fields['transaction_type'],
          # 'basic_amenities':other_fields['basic_amenities'],
          # 'lifestyle':other_fields['lifestyle'],
          'project':Project,
          'area':Area,
          'price':Price,
          'link':Link,

      }
      all_items.append(item)

  df1=pd.DataFrame(all_items)
  other_fields=[]
  for i in range(len(df1['link'])):
    print(i)
    item=link_data(df1['link'][i])
    other_fields.append(item)

  df2=pd.DataFrame(posted_by,columns=['posted_by'])
  df3=pd.DataFrame(other_fields)
  complete_df=pd.concat([df1,df2,df3],axis=1)
  return complete_df

data=dataset(base_url,2)
data.head()

# other_fields=[]
# for i in range(len(data['link'])):
#   item=link_data(data['link'][i])
#   other_fields.append(item)
# df_items=pd.DataFrame(all_items)
# df_items.head()

https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-green-life-hinjewadi-pune-678-sq-ft-to682-sq-ft-npspid-A54025688
https://www.99acres.com/1-bhk-bedroom-residential-apartments-for-sale-in-sbm-aviva-hinjewadi-pune-455-sq-ft-to475-sq-ft-npspid-C53563458
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-sbm-aviva-hinjewadi-pune-619-sq-ft-to622-sq-ft-npspid-Y53563460
https://www.99acres.com/residential-land-for-sale-in-aarohi-park-hinjewadi-pune-1076-sq-yard-to3228-sq-yard-npspid-U54774734
https://www.99acres.com/3-bhk-bedroom-residential-apartments-for-sale-in-kasturi-eon-homes-phase-3-hinjewadi-pune-945-sq-ft-to1282-sq-ft-npspid-H54789790
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-kasturi-eon-homes-phase-3-hinjewadi-pune-824-sq-ft-to935-sq-ft-npspid-B54789792
https://www.99acres.com/1-bhk-bedroom-residential-apartments-for-sale-in-vaishnavi-homes-marunji-pune-476-sq-ft-to489-sq-ft-npspid-H53654988
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-vaishnavi-homes-marunji-pune-638-sq-ft-to697-sq-ft-npspid-R53654990
https://www.99acres.com/1-bhk-bedroom-residential-apartments-for-sale-in-green-life-hinjewadi-pune-453-sq-ft-to465-sq-ft-npspid-P54025690
https://www.99acres.com/3-bhk-bedroom-residential-apartments-for-sale-in-shapoorji-joyville-sensorium-hinjewadi-pune-973-sq-ft-to979-sq-ft-npspid-O53037598
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-shapoorji-joyville-sensorium-hinjewadi-pune-565-sq-ft-to604-sq-ft-npspid-K53037596
https://www.99acres.com/1-bhk-bedroom-residential-apartments-for-sale-in-rama-livmo-phase-3-hinjewadi-pune-580-sq-ft-npspid-C54803470
https://www.99acres.com/1-bhk-bedroom-residential-apartments-for-sale-in-kolte-patil-oro-avenue-hinjewadi-pune-367-sq-ft-npspid-I55112394
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-kolte-patil-oro-avenue-hinjewadi-pune-551-sq-ft-npspid-V55112390
https://www.99acres.com/3-bhk-bedroom-residential-apartments-for-sale-in-shapoorji-joyville-sensorium-hinjewadi-pune-787-sq-ft-npspid-X55111784
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-shapoorji-joyville-sensorium-hinjewadi-pune-537-sq-ft-npspid-P55111782
https://www.99acres.com/1-bhk-bedroom-residential-apartments-for-sale-in-paranjape-blueridge-the-groves-hinjewadi-pune-445-sq-ft-npspid-E54679806
https://www.99acres.com/3-bhk-bedroom-residential-apartments-for-sale-in-kolte-patil-life-republic-hinjewadi-pune-991-sq-ft-npspid-V55185352
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-kolte-patil-life-republic-hinjewadi-pune-650-sq-ft-npspid-E55185348
https://www.99acres.com/3-bhk-bedroom-residential-apartments-for-sale-in-xrbia-township-marunji-pune-846-sq-ft-spid-D54835482
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-shapoorji-joyville-sensorium-hinjewadi-pune-537-sq-ft-to970-sq-ft-npspid-A55230898
https://www.99acres.com/3-bhk-bedroom-residential-apartments-for-sale-in-kolte-patil-r1-at-life-republic-hinjewadi-pune-978-sq-ft-to1199-sq-ft-npspid-K55169892
https://www.99acres.com/3-bhk-bedroom-residential-apartments-for-sale-in-kumar-megapolis-hinjewadi-pune-1305-sq-ft-to1495-sq-ft-npspid-G55211350
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-saarrthi-savvy-homes-hinjewadi-pune-775-sq-ft-npspid-O54762416
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-ace-augusta-hinjewadi-pune-678-sq-ft-npspid-L55151984
https://www.99acres.com/2-bhk-bedroom-residential-apartments-for-sale-in-ace-augusta-hinjewadi-pune-678-sq-ft-npspid-H70766720
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25

             project  ... transaction_type
0         Green Life  ...         New sale
1          SBM Aviva  ...         New sale
2          SBM Aviva  ...         New sale
3        Aarohi Park  ...         New sale
4  Kasturi Eon Homes  ...         New sale

[5 rows x 12 columns]